### ISSUE TITLE
Result different from enloc?

### ISSUE THREAD

**Issue by Zepeng-Mu** [xqwen/fastenloc#1]
Hi,

I am wondering whether fastENLOC gives different results from enloc?
Since I am trying to run enloc now, I am not sure if I should switch to fastENLOC.
If fastENLOC reports different region colocalization probability from enloc, then I will definitely switch to it.

Thanks so much!

**Comment by xqwen** [comment]
The enrichment results should be consistent with the original ENLOC. In fastenloc, we switch the LD unit for analysis based on eQTL analysis (based on information from DAP). So the results should have higher resolution. It also a bit difficult to compare the old ENLOC results with the new results from fastenloc because of this change. But I would definitely recommend switching to fastENLOC.
